image: Visual Studio 2017 RC
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
    - release
    - /^(.*\/)?ci-.*$/
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
notifications:
  - provider: Email
    subject: 'Build {{status}}'
    to:
      - topnguyen92@email.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true