#region	License
//------------------------------------------------------------------------------------------------
// <License>
//     <Copyright> 2017 © Top Nguyen → AspNetCore → Monkey </Copyright>
//     <Url> http://topnguyen.net/ </Url>
//     <Author> Top </Author>
//     <Project> Monkey → Business Interface </Project>
//     <File>
//         <Name> IAuthenticationBusiness.cs </Name>
//         <Created> 13/09/17 10:47:20 PM </Created>
//         <Key> 0b6435fb-3d3a-4fe1-ae17-a9703a45d61f </Key>
//     </File>
//     <Summary>
//         IAuthenticationBusiness.cs
//     </Summary>
// <License>
//------------------------------------------------------------------------------------------------
#endregion License

using Monkey.Core.Models.Auth;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Monkey.Business.Auth
{
    public interface IAuthenticationBusiness : IBaseBusiness
    {
        #region Get

        Task<LoggedInUserModel> GetLoggedInUserBySubjectAsync(string subject, CancellationToken cancellationToken = default);

        Task<LoggedInUserModel> GetLoggedInUserByRefreshTokenAsync(string refreshToken, CancellationToken cancellationToken = default);

        #endregion

        #region Sign In

        /// <summary>
        ///     Check user name and password is correct, not banned and already active 
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="password"></param>
        /// m
        void CheckValidSignIn(string userName, string password);

        LoggedInUserModel SignIn(string username, string password, out string refreshToken, int? clientId);

        #endregion

        #region Refresh Token

        /// <summary>
        ///     Expire all refresh token generated by sign in action, this method make user must sign
        ///     in again
        /// </summary>
        /// <param name="subject">          </param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        Task ExpireAllRefreshTokenAsync(string subject, CancellationToken cancellationToken = default);

        #endregion

        #region Get Password

        string GenerateTokenSetPassword(string userSubject, string email, out TimeSpan expireIn);

        string GenerateTokenConfirmEmail(string userSubject, string email, out TimeSpan expireIn);

        string GenerateTokenConfirmPhone(string userSubject, string phone, out TimeSpan expireIn);

        void ExpireTokenSetPassword(string token);

        void ExpireTokenConfirmEmail(string token);

        void ExpireTokenConfirmPhone(string token);

        #endregion

        #region Set Password

        Task SetPasswordAsync(string subject, string password, CancellationToken cancellationToken = default);

        /// <summary>
        ///     Active user via email, setup new username and password 
        /// </summary>
        /// <param name="subject">          </param>
        /// <param name="newUserName">      </param>
        /// <param name="newPassword">      </param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        Task ConfirmEmailAsync(string subject, string newUserName, string newPassword, CancellationToken cancellationToken = default);

        Task ConfirmPhoneAsync(string subject, string newUserName, string newPassword, CancellationToken cancellationToken = default);

        #endregion

        #region Validation

        bool IsExpireOrInvalidSetPasswordToken(string token);

        bool IsExpireOrInvalidConfirmEmailToken(string token);

        /// <summary>
        ///     Check refresh token is exist and not expire 
        /// </summary>
        /// <param name="clientId">    </param>
        /// <param name="refreshToken"></param>
        void CheckValidRefreshToken(string refreshToken, int? clientId);

        void CheckCurrentPassword(string currentPassword);

        #endregion
    }
}