#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> Monkey.Api </Project>
//     <File> 
//         <Name> Program.cs </Name>
//         <Created> 28 03 2017 10:19:01 AM </Created>
//         <Key> 29832439-583C-47C6-A80F-B93105D7109D </Key>
//     </File>
//     <Summary>
//         Program
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using System;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Text;

namespace Monkey
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Console.Title = "Monkey Web API";

            IWebHostBuilder hostBuilder =
                new WebHostBuilder()
                    .UseKestrel(options =>
                    {
                        options.AddServerHeader = false;
                    })
                    .UseWebRoot(Core.Constants.Setting.WebRoot)
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseIISIntegration()
                    .UseStartup<Startup>();

            hostBuilder.Build().Run();
        }
    }
}